/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facebook_imagepipeline_bpg_BpgImageInfo */

#ifndef _Included_com_facebook_imagepipeline_bpg_BpgImageInfo
#define _Included_com_facebook_imagepipeline_bpg_BpgImageInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facebook_imagepipeline_bpg_BpgImageInfo
 * Method:    getImageInfoFromBuf
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_facebook_imagepipeline_bpg_BpgImageInfo_getImageInfoFromBuf
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
