/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facebook_imagepipeline_nativecode_BpgTranscoder */

#ifndef _Included_com_facebook_imagepipeline_nativecode_BpgTranscoder
#define _Included_com_facebook_imagepipeline_nativecode_BpgTranscoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facebook_imagepipeline_nativecode_BpgTranscoder
 * Method:    getBmpBufferSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_facebook_imagepipeline_nativecode_BpgTranscoder_getBmpBufferSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_facebook_imagepipeline_nativecode_BpgTranscoder
 * Method:    decodeBodyBuffer
 * Signature: (Lcom/facebook/imagepipeline/bpg/BpgImageInfo;[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_facebook_imagepipeline_nativecode_BpgTranscoder_decodeBodyBuffer
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_facebook_imagepipeline_nativecode_BpgTranscoder
 * Method:    decodeFullImageBuffer
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_facebook_imagepipeline_nativecode_BpgTranscoder_decodeFullImageBuffer
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
